# Generated by Django 4.1.3 on 2023-08-12 23:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('academic_year', models.IntegerField(choices=[(-2, '-2'), (-1, '-1'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')])),
                ('phone_number', models.CharField(max_length=11)),
                ('phone_number2', models.CharField(max_length=11)),
                ('facebook_profile', models.TextField()),
                ('date_of_birth', models.DateField(default=datetime.date(2000, 1, 1))),
                ('school_name', models.TextField()),
                ('confession_father', models.CharField(choices=[('لا يوجد', 'لا يوجد'), ('ابونا تاردس', 'ابونا تادرس'), ('ابونا سيرافيم', 'ابونا سيرافيم'), ('ابونا تيمثاوس', 'ابونا تيمثاوس'), ('اب كاهن اخر', 'اب كاهن اخر')], default='لا يوجد', max_length=15)),
                ('hobbies', models.TextField()),
                ('health_problems', models.TextField(default='لا يوجد')),
                ('home_town', models.TextField(default='منوف')),
                ('home_region', models.TextField()),
                ('home_address', models.TextField()),
                ('how_to_church', models.TextField()),
                ('registered_in_church_list', models.BooleanField(default=False)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('father_phone_number1', models.CharField(blank=True, max_length=11)),
                ('father_phone_number2', models.CharField(blank=True, max_length=11)),
                ('father_facebook_profile', models.TextField(blank=True)),
                ('father_job', models.CharField(blank=True, max_length=100)),
                ('father_alive', models.BooleanField(default=True)),
                ('father_notes', models.TextField(blank=True)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('mother_phone_number1', models.CharField(blank=True, max_length=11)),
                ('mother_phone_number2', models.CharField(blank=True, max_length=11)),
                ('mother_facebook_profile', models.TextField(blank=True)),
                ('mother_job', models.CharField(blank=True, max_length=100)),
                ('mother_alive', models.BooleanField(default=True)),
                ('mother_notes', models.TextField(blank=True)),
                ('brothers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project2.student')),
            ],
        ),
    ]
