# Generated by Django 4.1.3 on 2023-08-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='brothers',
        ),
        migrations.AddField(
            model_name='student',
            name='brothers',
            field=models.ManyToManyField(blank=True, to='project2.student'),
        ),
    ]
