# Generated by Django 4.1.3 on 2023-08-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0003_student_absences_alter_student_confession_father_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='facebook_profile',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_facebook_profile',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='health_problems',
            field=models.CharField(blank=True, default='لا يوجد', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='hobbies',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_region',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='home_town',
            field=models.CharField(blank=True, default='منوف', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='how_to_church',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_facebook_profile',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
