# Generated by Django 4.1.3 on 2023-08-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0004_alter_student_facebook_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='absences',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='student',
            name='brothers',
        ),
        migrations.AddField(
            model_name='student',
            name='brothers',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
