# Generated by Django 4.1.3 on 2023-08-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0007_remove_student_brothers_student_brothers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='brothers',
            field=models.ManyToManyField(blank=True, default=list, null=True, to='project2.student'),
        ),
    ]
