# Generated by Django 4.1.3 on 2023-08-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0008_alter_student_brothers'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
