# Generated by Django 4.1.3 on 2023-08-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0010_attendancerecord_alter_student_brothers'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='students_present',
            field=models.TextField(blank=True),
        ),
    ]
