# Generated by Django 4.1.3 on 2023-08-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0013_attendancerecord_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='day_topic',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='day_verse',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='day_title',
            field=models.CharField(default='مدارس احد', max_length=50),
        ),
    ]
