# Generated by Django 4.1.3 on 2023-08-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0014_attendancerecord_day_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='day_title',
            field=models.CharField(choices=[('مدارس احد', 'مدارس احد'), ('يوم روحي', 'يوم روحي'), ('خلوة', 'خلوة'), ('يوم رياضي', 'يوم رياضي'), ('رحلة', 'رحلة'), ('الحان', 'الحان'), ('تسبحة', 'تسبحة'), ('عشية', 'عشية'), ('عيد', 'عيد')], default='مدارس احد', max_length=50),
        ),
    ]
