# Generated by Django 4.1.3 on 2023-08-24 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0015_alter_attendancerecord_day_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(default=datetime.datetime.today, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('date',)},
        ),
    ]
