# Generated by Django 4.1.3 on 2023-08-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0016_alter_attendancerecord_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='day_notes',
            field=models.TextField(blank=True),
        ),
    ]
