# Generated by Django 4.1.3 on 2023-08-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0019_alter_attendancerecord_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
