# Generated by Django 4.1.3 on 2023-08-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0020_student_attendance_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='students_eftekad_notyet',
            field=models.TextField(blank=True),
        ),
    ]
