# Generated by Django 4.1.3 on 2023-08-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0023_attendancerecord_academic_year_attendance_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='academic_year_attendance_rate',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='class_attendance_rate',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
