# Generated by Django 4.1.3 on 2023-09-02 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0024_remove_attendancerecord_academic_year_attendance_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('phone_number', models.CharField(blank=True, max_length=11)),
                ('phone_number2', models.CharField(blank=True, max_length=11)),
                ('home_town', models.CharField(blank=True, default='منوف', max_length=255)),
                ('home_region', models.CharField(blank=True, max_length=255)),
                ('home_address', models.CharField(blank=True, max_length=255)),
                ('facebook_profile', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date(2000, 1, 1))),
                ('class_number', models.CharField(blank=True, choices=[('12', '12'), ('34', '34'), ('56', '56')], max_length=10)),
                ('absences', models.IntegerField(blank=True, default=0, null=True)),
                ('attendance_rate', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='servants_attended',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='servants_eftekad_notyet',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student',
            name='responsible_servant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='day_title',
            field=models.CharField(choices=[('مدارس احد', 'مدارس احد'), ('يوم روحي', 'يوم روحي'), ('خلوة', 'خلوة'), ('يوم رياضي', 'يوم رياضي'), ('رحلة', 'رحلة'), ('الحان', 'الحان'), ('تسبحة', 'تسبحة'), ('عشية', 'عشية'), ('عيد', 'عيد'), ('اخري', 'اخري')], default='مدارس احد', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, choices=[('الاسقفية', 'الاسقفية'), ('الاقباط الابتدائية', 'الاقباط الابتدائية'), ('التحرير', 'التحرير'), ('هابي سكول', 'هابي سكول'), ('برهيم التجريبية', 'برهيم التجريبية'), ('سدود التجريبية', 'سدود التجريبية'), ('الشيخ زويل', 'الشيخ زويل'), ('اخري', 'اخري')], max_length=255),
        ),
    ]
