# Generated by Django 4.1.3 on 2023-09-02 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project2', '0025_servant_attendancerecord_servants_attended_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servant',
            old_name='absences',
            new_name='absences_number',
        ),
    ]
